name: 'LINE push message'
description: 'LINE push message action using GitHub actions'
inputs:
  user-id:
    description: 'User ID to push message'
    required: true
  message:
    description: "Text message to push message"
    default: "You are commited on repository"
runs:
  using: 'node12'
  main: 'dist/index.js'
