name: 'LINE push message'
description: 'LINE push message action using GitHub actions'
branding:
  icon: message-square  
  color: green
inputs:
  user-id:
    description: 'User ID to push message'
    required: true
  message:
    description: "Text message to push message"
    default: "You are commited on repository"
  channel-access-token:
    description: "Channel access token"
    required: true
runs:
  using: 'node12'
  main: 'dist/index.js'
