on: [push]

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to say hello
    steps:
    - name: Push LINE message
      uses: ufoo68/line-push-message@v1.1
      with:
        user-id: ${{ secrets.USER_ID }}
        message: 'test'