on: [push]

jobs:
  line_push_message_job:
    runs-on: ubuntu-latest
    name: LINE push message
    steps:
    - name: Push LINE message
      uses: ufoo68/line-push-message@v1.2
      with:
        user-id: ${{ secrets.USER_ID }}
        message: 'test'
        channal-access-token: ${{ secrets.CHANNEL_ACCESS_TOKEN }}